image: Visual Studio 2019

version: '0.2.0-{build}'

install:
  - cmake --version # expect >= 3.16
  - ninja --version # expect >= 1.10

  - set QT_VERSION=5.15.1
  - set Qt5_PATH=C:\Qt\%QT_VERSION%\msvc2019_64
  - set QT_QPA_PLATFORM_PLUGIN_PATH=%Qt5_PATH%\plugins\platforms
  - set PATH=%PATH%;%Qt5_PATH%\bin;%
  - set BOOST_ROOT=C:\Libraries\boost_1_73_0

  # Updates PATH to support command-line usage of compiler
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%

  # Copy Qt runtime binaries to our bin folder
  - Xcopy /E /I %Qt5_PATH%\bin\*.dll %cd%\bin

  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -G Ninja

build_script:
  - ninja

test_script:
  - cd test
  - testTactile
