name: "CI: macOS"

on: [ push ]

env:
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
  VCPKG_TARGET_TRIPLET: x64-osx-tactile
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/vcpkg/bincache
  VCPKG_CACHE_EDITION: 1

jobs:
  macos-latest-test:
    runs-on: macos-latest
    if: contains(github.event.head_commit.message, '[skip-ci]') == false
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          brew update
          brew install cmake
          brew install ninja

      - name: Cache Vcpkg
        id: restore-vcpkg-and-artifacts
        uses: actions/cache@v3
        with:
          path: |
            ${{env.VCPKG_ROOT}}
            !${{env.VCPKG_ROOT}}\buildtrees
            !${{env.VCPKG_ROOT}}\packages
            !${{env.VCPKG_ROOT}}\downloads
            !${{env.VCPKG_ROOT}}\installed
          key: tactile-macos-vcpkg-${{hashFiles('vcpkg.json')}}-${{env.VCPKG_CACHE_EDITION}}

      - name: Install Vcpkg
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: Create directory ${{env.VCPKG_DEFAULT_BINARY_CACHE}}
        run: mkdir -p ${{env.VCPKG_DEFAULT_BINARY_CACHE}}

      - name: Register custom Vcpkg triplet file
        run: cp "cmake/x64-osx-tactile.cmake" "$VCPKG_ROOT/triplets/community/x64-osx-tactile.cmake"

      - name: Generate build files
        run: |
          mkdir build && cd build
          cmake .. -GNinja \
                   -DCMAKE_BUILD_TYPE=Debug \
                   -DVCPKG_TARGET_TRIPLET=${{env.VCPKG_TARGET_TRIPLET}} \
                   -DTACTILE_USE_SANITIZERS=OFF \
                   -DTACTILE_BUILD_TESTS=ON \
                   --log-level=DEBUG

      - name: Build
        run: ninja -C build

      - name: Run core unit tests
        working-directory: ./build/debug
        run: ./tactile-core-test

      - name: Run TMJ format unit tests
        working-directory: ./build/debug
        run: ./tactile-tmj-format-test
