name: "CI: macOS"

on: [ push ]

env:
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
  VCPKG_TARGET_TRIPLET: x64-osx
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/vcpkg/bincache
  VCPKG_CACHE_EDITION: 1

jobs:
  macos-latest-test:
    runs-on: macos-latest
    if: contains(github.event.head_commit.message, '[skip-ci]') == false
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        shell: bash
        run: |
          brew update
          brew install cmake
          brew install ninja

      - name: Install Boost
        id: install-boost
        uses: MarkusJx/install-boost@v2.4.3
        with:
          boost_version: 1.80.0

      - name: Cache Vcpkg
        id: restore-vcpkg-and-artifacts
        uses: actions/cache@v3
        with:
          path: |
            ${{env.VCPKG_ROOT}}
            !${{env.VCPKG_ROOT}}\buildtrees
            !${{env.VCPKG_ROOT}}\packages
            !${{env.VCPKG_ROOT}}\downloads
            !${{env.VCPKG_ROOT}}\installed
          key: tactile-macos-vcpkg-${{hashFiles('vcpkg.json')}}-${{env.VCPKG_CACHE_EDITION}}

      - name: Install Vcpkg
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: Create directory ${{env.VCPKG_DEFAULT_BINARY_CACHE}}
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        shell: bash
        run: mkdir -p ${{env.VCPKG_DEFAULT_BINARY_CACHE}}

      - name: Make build directory
        shell: bash
        run: mkdir build

      - name: Generate build files
        working-directory: ./build
        shell: bash
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DVCPKG_TARGET_TRIPLET=${{env.VCPKG_TARGET_TRIPLET}} -GNinja
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      - name: Build
        working-directory: ./build
        shell: bash
        run: ninja

      - name: Run tests
        working-directory: ./build/test
        shell: bash
        run: ./TactileTests