name: "CI: Windows"

on: [ push, pull_request ]

env:
  VCPKG_ROOT: ${{github.workspace}}\vcpkg
  VCPKG_TARGET_TRIPLET: x64-windows-static-md
  VCPKG_DEFAULT_TRIPLET: x64-windows-static-md
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}\vcpkg\bincache
  VCPKG_CACHE_EDITION: 1

jobs:
  windows-latest-test:
    runs-on: windows-latest
    if: contains(github.event.head_commit.message, '[skip-ci]') == false
    steps:
      - uses: actions/checkout@main
      - uses: ilammy/msvc-dev-cmd@master
      - uses: lukka/get-cmake@latest

      - name: Cache Vcpkg
        id: restore-vcpkg-and-artifacts
        uses: actions/cache@v2
        with:
          path: |
            ${{env.VCPKG_ROOT}}
            !${{env.VCPKG_ROOT}}\buildtrees
            !${{env.VCPKG_ROOT}}\packages
            !${{env.VCPKG_ROOT}}\downloads
            !${{env.VCPKG_ROOT}}\installed
          key: tactile-windows-vcpkg-${{hashFiles('vcpkg.json')}}-${{env.VCPKG_CACHE_EDITION}}

      - name: Install Vcpkg
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
          .\vcpkg\vcpkg integrate install

      - name: Create directory ${{env.VCPKG_DEFAULT_BINARY_CACHE}}
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        shell: powershell
        run: mkdir -p ${{env.VCPKG_DEFAULT_BINARY_CACHE}}

      - name: Create build directory
        shell: cmd
        run: mkdir build

      - name: Generate build files
        working-directory: ./build
        shell: cmd
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DVCPKG_TARGET_TRIPLET=${{env.VCPKG_TARGET_TRIPLET}} -GNinja

      - name: Build
        working-directory: ./build
        shell: cmd
        run: ninja

      - name: Run tests
        working-directory: ./build/build
        shell: cmd
        run: TactileTests.exe